name: Docker Image CI

on:
  push:
    branches: 
    - master
    paths: 
    - fragbots

jobs:
  
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./fragbots
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version-file: './go.mod'
    - run: go version
